custom_authentication/config/routes.rb
Rails.application.routes.draw do

  root "users#root_page"
  get "/login", to: "users#login", as: "login"
  post "/login", to: "users#log_in", as: "log_in"
  get "/logout", to: "users#logout", as: "logout"
  resources :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Defines the root path route ("/")
  # root "articles#index"

end

custom_authentication/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

custom_authentication/app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    has_secure_token :remember_token
    validates :username, :email,  presence: true
    validates :username, :email, uniqueness:  true
    validates :password, confirmation: true, on: :create
    mount_uploader :avatar, AvatarUploader
    serialize :avatars, JSON
end

custom_authentication/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    helper_method :current_user
    helper_method :logged_in? 
    before_action :require_login?

    def logged_in?
        session[:current_user_id] 
    end  

    private 
    def current_user 
        @_current_user ||= session[:current_user_id] &&
        User.find_by(id: session[:current_user_id])
    end

    def require_login?
        unless logged_in?
        flash[:error] = "You must be logged in to access this section"
        redirect_to login_path # halts request cycle
        end
    end
end

custom_authentication/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[show edit update destroy]
  skip_before_action :require_login?

  def root_page
  end

  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)
    respond_to do |format|
      if @user.save
        UserMailer.with(user: @user).welcome_email.deliver_now
        format.html { redirect_to login_path, notice: "User was successfully created." }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(email: user_params[:email])
        UserMailer.with(user: @user).update_email.deliver_now
        format.html { redirect_to root_path, notice: "User was successfully updated." }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def login
    @user = User.new
  end

  def log_in
    user = User.find_by(email: user_params[:email])
    if user
      if user.password = user_params[:password]
        flash[:notice] = "Successfully loged in."
        session[:current_user_id] = user.id
        redirect_to root_path
      else
        flash[:notice] = "Wrong credentials."
        redirect_to login_path
      end
    else
      flash[:notice] = "User does not exist."
      redirect_to login_path
    end
  end

  def logout
    session.clear
    cookies.delete(:name)
    redirect_to login_path
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def user_params
    params.require(:user).permit(:username, :email, :password, :remember_token, :avatar)
  end
end

custom_authentication/app/helpers/application_helper.rb
module ApplicationHelper
end

custom_authentication/app/helpers/users_helper.rb
module UsersHelper
end

custom_authentication/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CustomAuthentication</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.1.3/dist/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.3/dist/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.1.3/dist/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css">
  </head>



  <body>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="/">Practical</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      



<% if current_user %>

      <li class="nav-item  d-none d-lg-inline-block mr-auto mb-3 mb-md-0 ml-md-3">
        <a> Hello <%= current_user.username  %></a>
      </li>
      <li class="nav-item d-none d-lg-inline-block  mb-3 mb-md-0 ml-md-3">
         <%= link_to "Edit", edit_user_path(current_user)%>  
      </li>
    
      <li class="nav-item d-none d-lg-inline-block mb-3 mb-md-0 ml-md-3">
        <a class="nav-link" href="/logout">logout</a>
      </li>
        <div class="d-flex ml-auto justify-content-end">
          <img src= <%= current_user.avatar %> alt="My Image" class="navbar-img  rounded-circle" width="50" height="50">
      </div>
      <% else %>
        <li class="nav-item d-none d-lg-inline-block mb-3 mb-md-0 ml-md-3">
        <a class="nav-link" href="/users/new">sing Up</a>
      </li>
         <li class="nav-item d-none d-lg-inline-block mb-3 mb-md-0 ml-md-3">
        <a class="nav-link" href="/login">Log In</a>
      </li>
<%end %>

  </div>
</nav>



  <% if notice %>
  <p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>

<div class="container">
    <%= yield %>
    </div>
  </body>
</html>

custom_authentication/app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :username, style: "display: block" %>
    <%= form.text_field :username, required: true  %>
  </div>

  <div>
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email, required: true  %>
  </div>

  <div>
    <%= form.label :password, style: "display: block" %>
    <%= form.password_field :password %>
  </div>

  <div>
    <%= form.label :password_confirmation, style: "display: block" %>
    <%= form.password_field :password_confirmation %>
  </div>

  <%= form.label :avatar, style: "display: block" %>
  <%= form.file_field :avatar %>
  
  <div>
    <%= form.submit %>
  </div>
<% end %>

custom_authentication/app/views/users/_user.html.erb
<div id="<%= dom_id user %>">
  <p>
    <strong>Username:</strong>
    <%= user.username %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= user.email %>
  </p>

  <p>
    <strong>Password digest:</strong>
    <%= user.password_digest %>
  </p>

  <p>
    <strong>Remember token:</strong>
    <%= user.remember_token %>
  </p>

</div>

custom_authentication/app/views/users/edit.html.erb
<h1>Editing Email</h1>

<%= form_with(model: @user) do |form| %>



  <div>
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email, required: true  %>
  </div>


  <div>
    <%= form.submit %>
  </div>
<% end %>

<br>

<div>
  <%= link_to "Show this user", @user %> |
  <%= link_to "Back to users", users_path %>
</div>

custom_authentication/app/views/users/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Users</h1>

<div id="users">
  <% @users.each do |user| %>
    <%= render user %>
    <p>
      <%= link_to "Show this user", user %>
    </p>
  <% end %>
</div>

<%= link_to "New user", new_user_path %>

custom_authentication/app/views/users/login.html.erb
<h1>Login</h1>
<%=  form_with(url: log_in_path(@user), model: @user, method: :post ) do |f| %>

<%= f.label :email%>
<%= f.text_field :email  %>


<%= f.label :password %>
<%= f.password_field :password %>


<%= f.submit "login"%>
<% end %>

custom_authentication/app/views/users/new.html.erb
<h1>New user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Back to users", users_path %>
</div>

custom_authentication/app/views/users/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @user %>

<div>
  <%= link_to "Edit this user", edit_user_path(@user) %> |
  <%= link_to "Back to users", users_path %>

  <%= button_to "Destroy this user", @user, method: :delete %>
</div>